artifacts_root: artifacts

preprocessing:
  root_dir: artifacts/preprocessing

landmarks_extraction:
  root_dir: artifacts/landmarks
  output_dir: artifacts/landmarks

model:
  root_dir: model
  model_weight_dir: model/model_weight.hdf5
